# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /qna:
    get:
      operationId: "assistant.ping"
      tags:
        - "Assistant"
      summary: "Ping"
      responses:
        "200":
          description: "Ping"
    post:
      operationId: "assistant.ask"
      summary: "Ask question to assistant"
      requestBody:
        description: "Ask question to assistant"
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: "Assistant Responded"
